[project]
name = "trade-republic-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "fastmcp>=2.3.1",
    "pandas>=2.2.3",
    "pydantic-ai[mcp]>=0.1.10",
]
